# Dependencies
gems:
#    - jekyll-mentions
#    - jemoji
#    - jekyll-redirect-from
    - jekyll-sitemap

markdown:       redcarpet
redcarpet:
    extensions: 
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - with_toc_data
        - strikethrough
        - space_after_headers
        - superscript
        - underline

pygments:       false
highlighter:    false

# Permalinks & pagination
permalink:      date
paginate:       5

# Setup
title:          'Da-eto'
tagline:        'Beata stultica'
url:            https://da-eto-ya.github.io
enforce_ssl:    da-eto-ya.github.io

author:
    name:       'Ilya Pleshakov'
    email:      'da-eto@ya.ru'

