# Dependencies
gems:
#    - jekyll-mentions
#    - jemoji
#    - jekyll-redirect-from
    - jekyll-sitemap

markdown: redcarpet
redcarpet:
    extensions: 
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - with_toc_data
        - strikethrough
        - space_after_headers
        - superscript
        - footnotes
#        - underline

highlighter:    null

# Permalinks & pagination
permalink:      date
paginate:       5

# Setup
title:          'Da-eto'
tagline:        'Beata stultica'
url:            http://da-eto.info
#enforce_ssl:    da-eto.info
enforce_ssl:    false

author:
    name:       'Ilya Pleshakov'
    email:      'da-eto@ya.ru'

exclude:
    - vendor
