# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Da-eto'
tagline:          'Programming exercises'
description:      'Programming exercises from <a href="https://github.com/da-eto-ya"><i class="fa fa-github"></i> da-eto-ya</a>'
url:              http://da-eto-ya.github.io

author:
  name:           'Ilya Pleshakov'
  url:            http://da-eto-ya.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
    repo:           https://github.com/da-eto-ya
