# Dependencies
gems:
#    - jekyll-mentions
#    - jemoji
#    - jekyll-redirect-from
    - jekyll-sitemap

markdown:       redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]

highlighter:    false

# Permalinks & pagination
permalink:      "/:year/:month/:title.html"
paginate:       5

# Setup
title:          'Da-eto'
tagline:        'Beata stultica'
description:    'Beata stultica (da-eto)'
url:            http://da-eto-ya.github.io

author:
    name:       'Ilya Pleshakov'
    url:        http://da-eto-ya.github.io

defaults:
    -
        scope:
            path:   ""
            type:   "post"
        values:
            author: "Ilya Pleshakov"
            comments: true
    -
        scope:
            path:   ""
            type:   "page"
        values:
            comments: false

# Custom vars

